version: "3"
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/volumes/walltaker_database2:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    volumes:
      - ./:/ror
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - .env
